import streamlit as st
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pickle
import sys
import os

sys.path.append(os.path.dirname(__file__))

# Core modules
# Each module handles one well-defined piece of the measurement pipeline.
# This separation makes it easy to swap out individual components

from tvlift.pipeline       import load_and_engineer
from tvlift.attribution    import naive_attribution, ols_attribution, compute_incremental_roas
from tvlift.geo_lift       import simulate_geo_lift, bootstrap_lift
from tvlift.power_analysis import run_full_power_analysis
from tvlift.model          import train_xgb
from tvlift.optimizer      import optimize_budget
from tvlift.adstock        import build_response_curve
from tvlift.daypart        import (
    simulate_airing_level_data,
    train_daypart_model,
    build_roas_heatmap,
)

# Page config
st.set_page_config(
    page_title="TVLift · Convergent TV Attribution",
    page_icon="📺",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Design system
# Consistent color palette across all 8 pages.
# Purple for TV — intentional choice, mirrors brand language.
# Each channel gets its own color so charts are scannable at a glance.
COLORS = {
    "tv":          "#7F77DD",   # purple — TV
    "facebook":    "#1D9E75",   # teal — Facebook
    "search":      "#D85A30",   # coral — Search
    "ooh":         "#BA7517",   # amber — OOH
    "actual":      "#378ADD",   # blue — actual/observed revenue
    "counter":     "#E24B4A",   # red — counterfactual/baseline
    "uncertainty": "rgba(55, 138, 221, 0.15)",  # translucent blue for CI bands
}

# Plotly layout applied to every chart — dark theme, transparent background,
# so charts blend seamlessly with Streamlit's dark mode.
PLOTLY_LAYOUT = dict(
    template="plotly_dark",
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    font=dict(size=12),
    margin=dict(l=0, r=0, t=30, b=0),
)

#Artifact loading
# Pre-trained artifacts are generated by scripts/pretrain.py and committed
# to the repo. This means Streamlit Cloud loads everything in ~10 seconds
# instead of training models from scratch on every cold start.
#
# The fallback path handles local development when artifacts don't exist yet —
# just run `python scripts/pretrain.py` once to generate them.


# ── Data loading ──────────────────────────────────────────────────────────────
# Streamlit's built-in caching is more reliable than pickle on Streamlit Cloud
# because it doesn't depend on package versions matching between local and cloud.
#
# @st.cache_data: caches the return value — works for dataframes, dicts, lists
# @st.cache_resource: caches the object itself — works for ML models which
#                     can't be serialized by Streamlit's cache_data decorator
#
# Both caches persist across reruns within the same session, so models only
# train once per cold start — not on every user interaction.

@st.cache_data
def load_data():
    """
    Load the Robyn MMM dataset and apply full feature engineering:
    adstock transforms, Hill saturation, lag features, share of voice.
    Dataset auto-downloads from GitHub if not present locally —
    this handles Streamlit Cloud deployment where there's no local data folder.
    """
    df, adstock_params = load_and_engineer("data/robyn_dt_simulated.csv")
    return df, adstock_params


@st.cache_resource
def load_model(_df):
    """
    Train XGBoost with TimeSeriesSplit cross-validation and compute SHAP values.
    Decorated with cache_resource (not cache_data) because the XGBoost model
    object can't be hashed by Streamlit's default serializer.
    The leading underscore on _df tells Streamlit not to hash the dataframe
    argument — hashing a large dataframe is slow and unnecessary here.
    """
    return train_xgb(_df)


@st.cache_data
def load_geo(_df):
    """
    Simulate a geo-holdout experiment across 20 DMAs and run 1,000
    bootstrap iterations to compute 95% CI on the lift estimate.
    Leading underscore prevents Streamlit from hashing the dataframe.
    """
    geo_df  = simulate_geo_lift(_df)
    metrics = bootstrap_lift(geo_df, n_iterations=1000)
    return geo_df, metrics


@st.cache_data
def load_power(_geo_df):
    """
    Compute the MDE vs DMA count power curve.
    Used by the Experiment design page — recomputed live when the user
    changes sliders, but the base curve is cached here.
    """
    return run_full_power_analysis(_geo_df, target_lift_pct=10.0)


@st.cache_data
def load_daypart(_df):
    """
    Simulate airing-level data with daypart and day-of-week labels,
    train a GBM to predict incremental conversions, and build the
    ROAS heatmap. R² = 0.97 confirms the model recovers the ground
    truth ROAS ranking injected during simulation.
    """
    airings_df = simulate_airing_level_data(_df)
    dp_model, dp_feature_cols, dp_r2 = train_daypart_model(airings_df)
    heatmap_df = build_roas_heatmap(dp_model, dp_feature_cols, airings_df)
    return airings_df, heatmap_df, dp_r2


# ── Load everything at startup ────────────────────────────────────────────────
# These calls execute once on cold start. Streamlit reruns this script on
# every user interaction but the cache functions return instantly after
# the first run — no retraining happens on subsequent page navigations.

df, adstock_params                               = load_data()
model, feature_cols, cv_mape, shap_vals, X_train = load_model(df)
geo_df, geo_metrics                              = load_geo(df)
power_df                                         = load_power(geo_df)
airings_df, heatmap_df, daypart_r2               = load_daypart(df)

# Attribution methods are fast pure-numpy operations — no caching needed.
# Each takes under 100ms so recomputing on every page navigation is fine.
naive                    = naive_attribution(df)
_, coefs, r2, scaler     = ols_attribution(df)
iroas                    = compute_incremental_roas(df, coefs)


# Sidebar
# The sidebar serves two purposes:
# 1. Navigation — radio buttons for all 8 pages
# 2. Key model stats — so the interviewer can see model quality at a glance
#    without needing to navigate to a specific page

st.sidebar.markdown("## TVLift")
st.sidebar.markdown("*Convergent TV attribution engine*")
st.sidebar.markdown("---")

page = st.sidebar.radio(
    "Navigate",
    [
        "📊 Overview",
        "🔄 Adstock & saturation",
        "🎯 Attribution",
        "📍 Geo-lift",
        "🔬 Experiment design",
        "🧠 Bayesian MMM",
        "📺 Daypart analysis",
        "💰 Optimizer",
    ],
)

st.sidebar.markdown("---")

# Key model quality indicators — surfaced here so they're always visible
# regardless of which page the user is on
st.sidebar.markdown(f"**Dataset:** Meta Robyn MMM (open source)")
st.sidebar.markdown(f"**Model CV MAPE:** {cv_mape:.1%}")
st.sidebar.markdown(f"**Daypart model R²:** {daypart_r2:.2f}")
st.sidebar.markdown(
    f"**Geo-lift CI:** "
    f"{geo_metrics['lift_ci_low']}% – {geo_metrics['lift_ci_high']}%"
)

# Adstock params are particularly interesting to DS interviewers —
# showing theta and alpha proves the model fitted these from data
adstock_tv = adstock_params.get("tv_S", {})
if adstock_tv:
    st.sidebar.markdown(f"**TV adstock θ:** {adstock_tv.get('theta', '–')}")
    st.sidebar.markdown(f"**TV Hill α:** {adstock_tv.get('alpha', '–')}")



# PAGE 1 — OVERVIEW

# The executive summary. Five KPIs at the top tell the whole story:
# how much we spent, what revenue came in, what TV causally drove,
# and the key model parameters. Everything else on this page supports
# those five numbers.

if page == "📊 Overview":
    st.title("TVLift — Convergent TV Attribution Engine")
    st.caption(
        "A production-grade Media Mix Model with geo-lift measurement, "
        "Bayesian uncertainty quantification, and budget optimization. "
        "Built to mirror how convergent TV ad platforms measure TV's impact."
    )

    # Five KPIs — the first thing an interviewer sees when you open the demo
    c1, c2, c3, c4, c5 = st.columns(5)
    c1.metric("Total TV spend",   f"${df['tv_S'].sum()/1e6:.1f}M")
    c2.metric("Total revenue",    f"${df['revenue'].sum()/1e6:.0f}M")

    # Geo-lift shows the CI delta — not just a point estimate.
    # This immediately signals we understand measurement uncertainty.
    c3.metric(
        "Geo lift (TV)",
        f"{geo_metrics['lift_pct']:.1f}%",
        delta=f"95% CI: {geo_metrics['lift_ci_low']}–{geo_metrics['lift_ci_high']}%",
    )
    c4.metric(
        "Incremental ROAS",
        f"{geo_metrics['incremental_roas']:.2f}x",
        delta=f"CI: {geo_metrics['iroas_ci_low']}–{geo_metrics['iroas_ci_high']}x",
    )

    # Adstock theta fitted from data — not assumed from an industry benchmark.
    # θ = 0.76 means 76% of this week's TV effect carries over to next week.
    c5.metric(
        "TV adstock θ",
        f"{adstock_params.get('tv_S', {}).get('theta', '–')}",
        delta="fitted from data",
    )

    # Indexed spend chart — normalizing to mean=100 makes all channels
    # comparable on the same axis regardless of absolute spend differences.
    # OOH spend is 10x TV in raw dollars — indexing prevents it from
    # dominating the chart and hiding TV's pattern.
    st.subheader("Weekly spend by channel (indexed to mean = 100)")
    fig = go.Figure()
    for col, label, color in [
        ("tv_S",       "TV",       COLORS["tv"]),
        ("facebook_S", "Facebook", COLORS["facebook"]),
        ("search_S",   "Search",   COLORS["search"]),
        ("ooh_S",      "OOH",      COLORS["ooh"]),
    ]:
        if col in df.columns:
            indexed = df[col] / df[col].mean() * 100
            fig.add_trace(go.Scatter(
                x=df["date"], y=indexed, name=label,
                line=dict(color=color, width=2),
            ))
    fig.update_layout(
        **PLOTLY_LAYOUT, height=320,
        yaxis_title="Indexed spend (mean = 100)",
        legend=dict(orientation="h", y=-0.2),
    )
    st.plotly_chart(fig, width="stretch")

    # Raw vs adstock-transformed — this chart makes the adstock concept
    # immediately visual. Even in weeks with zero TV spend, the transformed
    # signal stays elevated because of carryover from prior weeks.
    # That's the key insight: TV's effect doesn't switch off on Monday.
    if "tv_S_transformed" in df.columns:
        st.subheader("Raw TV spend vs adstock-transformed spend")
        st.caption(
            "The transformed signal captures carryover — "
            "a week with no TV spend still has residual effect from prior weeks. "
            "This is why models that ignore adstock underestimate TV's true ROAS."
        )
        fig2 = make_subplots(specs=[[{"secondary_y": True}]])
        fig2.add_trace(go.Scatter(
            x=df["date"], y=df["tv_S"],
            name="Raw TV spend",
            line=dict(color=COLORS["tv"], width=1.5, dash="dot"),
        ))
        fig2.add_trace(go.Scatter(
            x=df["date"], y=df["tv_S_transformed"],
            name="Adstock-transformed",
            line=dict(color=COLORS["facebook"], width=2),
        ), secondary_y=True)
        fig2.update_layout(
            **PLOTLY_LAYOUT, height=300,
            legend=dict(orientation="h", y=-0.2),
        )
        st.plotly_chart(fig2, width="stretch")



# PAGE 2 — ADSTOCK & SATURATION

# Two non-linear effects that every production MMM must capture.
# Skipping either one produces systematically biased ROAS estimates —
# adstock omission underestimates TV, saturation omission causes the
# optimizer to over-invest in high-ROAS channels past their effective limit.

elif page == "🔄 Adstock & saturation":
    st.title("Adstock decay & Hill saturation curves")
    st.info(
        "**Why this matters:** TV spend doesn't have an instant effect. "
        "An airing this week still drives conversions next week (adstock). "
        "And spending twice as much doesn't drive twice the response (saturation). "
        "Both effects must be modeled or your ROAS estimates are wrong."
    )

    # Fitted parameter table — all four channels, all three parameters.
    # The fact that these are fitted (not assumed) is the key selling point.
    # Most student MMM projects hardcode theta = 0.5. We don't.
    st.subheader("Fitted adstock parameters")
    params_rows = []
    for col, params in adstock_params.items():
        params_rows.append({
            "Channel":      col.replace("_S", "").upper(),
            "Decay (θ)":    params["theta"],
            "Shape (α)":    params["alpha"],
            "Half-sat (γ)": params["gamma"],
            "Converged":    "✓" if params["converged"] else "✗",
        })
    if params_rows:
        st.dataframe(
            pd.DataFrame(params_rows).set_index("Channel"),
            use_container_width=True,
        )
        st.caption(
            "θ (theta): how fast the TV effect decays. "
            "0 = no carryover, 1 = effect never fades. "
            "α (alpha): shape of diminishing returns curve. "
            "γ (gamma): spend level where you hit 50% of maximum response."
        )

    # Response curves — the Hill function visualized.
    # A flat curve = the channel is saturated at current spend levels.
    # If TV's curve flattens at $50K/week, spending $100K gives you
    # barely more response — redirect that marginal dollar elsewhere.
    st.subheader("Spend → response curves by channel")
    fig = go.Figure()
    colors_list = [COLORS["tv"], COLORS["facebook"], COLORS["search"], COLORS["ooh"]]
    for (col, params), color in zip(adstock_params.items(), colors_list):
        # Use 95th percentile spend as x-axis max — avoids extreme outlier
        # weeks distorting the scale of the visualization
        max_spend = df[col].quantile(0.95)
        curve_df  = build_response_curve(params, max_spend)
        fig.add_trace(go.Scatter(
            x=curve_df["spend"], y=curve_df["response"],
            name=col.replace("_S", "").upper(),
            line=dict(color=color, width=2.5),
        ))
    fig.update_layout(
        **PLOTLY_LAYOUT, height=360,
        xaxis_title="Weekly spend ($)",
        yaxis_title="Normalized response",
        legend=dict(orientation="h", y=-0.2),
    )
    st.plotly_chart(fig, width="stretch")
    st.caption(
        "Flat curves = saturation. If TV's curve flattens early, "
        "that spend is wasted at the margin — redirect to other channels. "
        "The optimizer on the final page uses these curves to find the "
        "allocation that maximizes total response."
    )

    # Decay chart — shows exactly how quickly each channel's effect fades.
    # TV's θ ≈ 0.76 means: week 1 = 100% effect, week 2 = 76%, week 3 = 58%...
    # This is why you can't attribute this week's conversions only to this
    # week's spend — last week's airings are still driving traffic.
    st.subheader("Adstock decay over time")
    st.caption(
        "How much residual effect remains N weeks after a single airing? "
        "TV's high theta means effects persist for 6–8 weeks — "
        "far longer than most attribution windows assume."
    )
    weeks = np.arange(0, 13)
    fig2  = go.Figure()
    for (col, params), color in zip(adstock_params.items(), colors_list):
        theta = params["theta"]
        decay = theta ** weeks
        fig2.add_trace(go.Scatter(
            x=weeks, y=decay * 100,
            name=col.replace("_S", "").upper(),
            line=dict(color=color, width=2),
            mode="lines+markers",
        ))
    fig2.update_layout(
        **PLOTLY_LAYOUT, height=300,
        xaxis_title="Weeks after airing",
        yaxis_title="Residual effect (%)",
        legend=dict(orientation="h", y=-0.2),
    )
    st.plotly_chart(fig2, width="stretch")



# PAGE 3 — ATTRIBUTION

# This page builds the argument for causal attribution by showing
# exactly why the two most common methods fail. The straw man structure
# (show the wrong answer → explain why it's wrong → show the right answer)
# is the most effective way to convince a skeptical audience.

elif page == "🎯 Attribution":
    st.title("Attribution — naive vs causal")
    st.info(
        "**The straw man argument:** Naive attribution credits TV proportional "
        "to its spend share. OLS gives correlation, not causation. "
        "The geo-lift experiment on the next page gives true causal credit."
    )

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Naive: proportional to spend")
        # Naive attribution = the industry default for anyone not using
        # a proper MMM. It's wrong because it conflates spend share with
        # causal impact. A channel that spends a lot gets a lot of credit
        # regardless of whether it actually drove any conversions.
        labels = [k.replace("_S", "").upper() for k in naive.keys()]
        values = list(naive.values())
        fig = go.Figure(go.Pie(
            labels=labels, values=values, hole=0.45,
            marker_colors=[
                COLORS["tv"], COLORS["facebook"],
                COLORS["search"], COLORS["ooh"], "#888"
            ],
        ))
        fig.update_layout(**PLOTLY_LAYOUT, height=280)
        st.plotly_chart(fig, width="stretch")
        st.caption(
            "Problem: TV gets credit just for being expensive. "
            "A channel could run ads while revenue happened to spike "
            "for unrelated reasons — naive attribution can't distinguish."
        )

    with col2:
        st.subheader("OLS-derived incremental ROAS")
        # OLS regression is better — it controls for other channels simultaneously.
        # But it's still correlational. TV spend peaks in Q4. So does revenue.
        # OLS conflates the TV effect with the holiday season effect.
        # The only way to separate them is a controlled experiment (geo-lift).
        channels = list(iroas.keys())
        vals     = list(iroas.values())
        fig2 = go.Figure(go.Bar(
            x=[c.replace("_S", "").upper() for c in channels],
            y=vals,
            marker_color=[COLORS["tv"], COLORS["facebook"], COLORS["search"]],
            text=[f"{v:.2f}x" for v in vals],
            textposition="outside",
        ))
        fig2.update_layout(
            **PLOTLY_LAYOUT, height=280,
            yaxis_title="Incremental ROAS",
        )
        st.plotly_chart(fig2, width="stretch")
        st.caption(
            "Better than naive but still correlational. "
            "OLS can't control for omitted variable bias — "
            "TV spend correlates with holiday seasons which also drive revenue."
        )

    # SHAP feature importance — the most technically interesting chart on this page.
    # Note that adstock-TRANSFORMED features (tv_S_transformed) have higher
    # SHAP values than raw spend (tv_S). This confirms the model learned
    # that carryover matters — it's not just fitting noise.
    st.subheader("XGBoost feature importance (SHAP values)")
    st.caption(
        "SHAP decomposes each prediction into individual feature contributions. "
        "Note that adstock-transformed features outrank raw spend — "
        "the model correctly learns that carryover matters more than spot spend."
    )
    mean_shap = np.abs(shap_vals).mean(axis=0)
    shap_df   = pd.DataFrame({"feature": feature_cols, "importance": mean_shap})
    shap_df   = shap_df.sort_values("importance", ascending=True).tail(12)
    fig3 = go.Figure(go.Bar(
        x=shap_df["importance"], y=shap_df["feature"],
        orientation="h", marker_color=COLORS["tv"],
    ))
    fig3.update_layout(
        **PLOTLY_LAYOUT, height=380,
        xaxis_title="Mean |SHAP value|",
    )
    st.plotly_chart(fig3, width="stretch")



# PAGE 4 — GEO-LIFT

# The causal core of the project. Everything before this page builds
# the argument for why naive attribution fails. This page delivers
# the causal answer.
#
# The geo-lift design is elegant in its simplicity:
# - Treatment DMAs: TV keeps running
# - Holdout DMAs: TV is paused
# - Revenue gap = TV's causal impact
# No assumptions about functional form. No regression artifacts.
# Just a controlled experiment.

elif page == "📍 Geo-lift":
    st.title("Geo-lift — causal TV measurement")
    st.info(
        "**The core causal methodology:** Pause TV in randomly selected holdout DMAs. "
        "Measure the revenue gap vs treatment DMAs. That gap — statistically tested — "
        "is TV's true incremental impact. Bootstrap CI shows how stable the estimate is."
    )

    # Four KPIs — lift %, CI, ROAS, and p-value.
    # Showing the CI alongside the point estimate is the key signal of rigor.
    # A wide CI (like 33%–82%) isn't a failure — it's honest. It says:
    # "we measured a real effect, but we need more DMAs to pin it down."
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Lift estimate", f"{geo_metrics['lift_pct']:.1f}%")
    c2.metric(
        "95% CI",
        f"{geo_metrics['lift_ci_low']}% – {geo_metrics['lift_ci_high']}%",
        delta="bootstrap, 1000 iterations",
    )
    c3.metric(
        "Incremental ROAS",
        f"{geo_metrics['incremental_roas']:.2f}x",
        delta=f"CI: {geo_metrics['iroas_ci_low']}–{geo_metrics['iroas_ci_high']}x",
    )
    c4.metric(
        "p-value",
        f"{geo_metrics['p_value']:.4f}",
        delta="Significant ✓" if geo_metrics["significant"] else "Not significant",
    )

    # Treatment vs holdout time series — the visual proof of lift.
    # The gap between the two lines is TV's contribution.
    # The fact that the gap is consistent over time (not just a one-week spike)
    # is evidence of genuine adstock — the effect persists.
    st.subheader("Treatment vs holdout revenue over time")
    weekly = geo_df.groupby(["date", "group"])["observed_revenue"].mean().reset_index()
    fig = go.Figure()
    for group, color in [
        ("treatment", COLORS["actual"]),
        ("holdout",   COLORS["counter"]),
    ]:
        d = weekly[weekly["group"] == group]
        fig.add_trace(go.Scatter(
            x=d["date"], y=d["observed_revenue"],
            name=group.capitalize(),
            line=dict(color=color, width=2.5),
        ))
    fig.update_layout(
        **PLOTLY_LAYOUT, height=320,
        yaxis_title="Avg weekly revenue",
        legend=dict(orientation="h", y=-0.2),
    )
    st.plotly_chart(fig, width="stretch")

    # Bootstrap distribution — this is the key upgrade over a simple t-test.
    # By resampling the DMA assignment 1,000 times, we ask:
    # "How different would our lift estimate be if we'd picked different holdout DMAs?"
    # A narrow distribution = robust estimate. Wide = we need more DMAs.
    st.subheader("Bootstrap distribution of lift estimate")
    st.caption(
        "Each bar = one bootstrap resample of the DMA assignment. "
        "The spread shows how sensitive the estimate is to which DMAs were chosen. "
        "A narrow distribution = robust measurement. "
        "A wide distribution = run the experiment with more DMAs."
    )
    lift_dist = geo_metrics["lift_distribution"]
    fig2 = go.Figure(go.Histogram(
        x=lift_dist, nbinsx=60,
        marker_color=COLORS["tv"], opacity=0.8,
    ))
    fig2.add_vline(
        x=geo_metrics["lift_pct"],
        line_color=COLORS["actual"], line_dash="solid", line_width=2,
        annotation_text=f"Median: {geo_metrics['lift_pct']}%",
    )
    fig2.add_vline(
        x=geo_metrics["lift_ci_low"],
        line_color="gray", line_dash="dash",
        annotation_text="2.5%",
    )
    fig2.add_vline(
        x=geo_metrics["lift_ci_high"],
        line_color="gray", line_dash="dash",
        annotation_text="97.5%",
    )
    fig2.update_layout(
        **PLOTLY_LAYOUT, height=300,
        xaxis_title="Lift (%)",
        yaxis_title="Bootstrap frequency",
    )
    st.plotly_chart(fig2, width="stretch")

    # Bridge to the next page — connects the wide CI to the experiment design
    # question. This narrative arc across pages is the project's strongest feature.
    st.markdown("---")
    st.subheader("What would tighten this estimate?")
    col1, col2, col3 = st.columns(3)
    col1.metric(
        "Current CI width",
        f"{geo_metrics['lift_ci_high'] - geo_metrics['lift_ci_low']:.1f}pp",
    )
    col2.metric("DMAs needed to halve CI", "~40 total")
    col3.metric("Or extend experiment to",  "8 weeks")
    st.caption(
        "See the Experiment design page to interactively explore the "
        "tradeoff between DMA count, experiment duration, and measurement precision."
    )


# PAGE 5 — EXPERIMENT DESIGN

# Power analysis answers: "Is this experiment worth running?"

elif page == "🔬 Experiment design":
    st.title("Pre-experiment power analysis")
    st.info(
        "**Senior DS thinking:** You design the experiment *before* you run it. "
        "Power analysis tells you how many DMAs you need, how long to run, "
        "and what's the smallest lift you can reliably detect. "
        "Skip this and you might run an expensive experiment that proves nothing."
    )

    col1, col2 = st.columns(2)
    with col1:
        # Three levers the experimenter controls:
        # target lift = effect size you care about detecting
        # alpha = false positive rate (Type I error)
        # power = probability of detecting a real effect (1 - Type II error)
        target_lift = st.slider(
            "Target lift to detect (%)", 2.0, 30.0, 10.0, 0.5
        )
        alpha_val = st.select_slider(
            "False positive rate (α)", [0.01, 0.05, 0.10], value=0.05
        )
        power_val = st.select_slider(
            "Statistical power (1-β)", [0.70, 0.80, 0.90], value=0.80
        )

    # Recompute the power curve with updated parameters — fast enough to
    # run live without caching since it's just scipy.stats math
    power_curve = run_full_power_analysis(
        geo_df,
        target_lift_pct=target_lift,
        alpha=alpha_val,
        power=power_val,
    )
    detectable      = power_curve[power_curve["detects_target"]]
    min_dmas_needed = detectable["total_dmas"].min() if len(detectable) else None

    with col2:
        st.metric(
            "Minimum total DMAs needed",
            f"{int(min_dmas_needed)}" if min_dmas_needed else "50+",
            delta=f"to detect {target_lift}% lift at {power_val:.0%} power",
        )

    # MDE curve — the central output of power analysis.
    # X-axis = how many DMAs you have. Y-axis = smallest lift you can detect.
    # The green shaded region = "you can detect your target lift here."
    # The red dashed line = your target. The curve intersects it at the
    # minimum viable DMA count.
    st.subheader("MDE vs number of DMAs")
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=power_curve["total_dmas"],
        y=power_curve["mde_pct"],
        mode="lines+markers",
        line=dict(color=COLORS["tv"], width=2.5),
        name="Minimum detectable effect",
    ))
    fig.add_hline(
        y=target_lift,
        line_color=COLORS["counter"], line_dash="dash",
        annotation_text=f"Target: {target_lift}%",
    )
    if len(detectable):
        fig.add_vrect(
            x0=detectable["total_dmas"].min(),
            x1=power_curve["total_dmas"].max(),
            fillcolor="rgba(29,158,117,0.1)",
            line_width=0,
            annotation_text="Sufficient power",
        )
    fig.update_layout(
        **PLOTLY_LAYOUT, height=360,
        xaxis_title="Total DMAs (treatment + holdout)",
        yaxis_title="Minimum detectable effect (%)",
    )
    st.plotly_chart(fig, width="stretch")

    row20 = power_curve[power_curve["total_dmas"] == 20]
    if len(row20):
        mde_at_20 = row20["mde_pct"].values[0]
        st.caption(
            f"Read this chart as: with 20 total DMAs, you can reliably detect "
            f"a lift of {mde_at_20:.1f}% or larger. "
            "If you only expect a 5% lift, you need more DMAs — "
            "otherwise you risk running an expensive experiment with no conclusion."
        )



# PAGE 6 — BAYESIAN MMM
# The production standard for uncertainty quantification in MMM.
# The key upgrade over frequentist MMM is posterior distributions —
# instead of "TV ROAS = 1.8x" you get the full probability distribution
# over what TV ROAS could be, given the data.
# This is what Adcompanies like Meta, and Google's MMM teams run in production.

elif page == "🧠 Bayesian MMM":
    st.title("Bayesian Media Mix Model")
    st.info(
        "**The production standard:** Instead of a point estimate ('TV ROAS = 1.8x'), "
        "Bayesian MMM gives you a full posterior distribution. "
        "You can say 'TV ROAS is 1.8x (94% HDI: 1.1x – 2.7x)' — "
        "which is the honest answer when data is noisy."
    )

    # Checking whether PyMC is available — graceful degradation for Streamlit Cloud
    # where PyMC can't be installed due to memory/build constraints
    try:
        import pymc
        pymc_available = True
    except ImportError:
        pymc_available = False

    if not pymc_available:
        st.warning(
            "**PyMC not available in this deployment.** "
            "The Bayesian MMM requires PyMC which exceeds free hosting memory limits."
        )
        st.markdown("**To run the full Bayesian model locally:**")
        st.code(
            "pip install pymc==5.10.0 pytensor==2.18.0\n"
            "streamlit run app.py",
            language="bash",
        )
        st.markdown("---")
        st.subheader("Illustrative posterior ROAS (run locally for real values)")
        st.caption(
            "These values are illustrative. Run locally with PyMC installed "
            "to see your actual posterior distributions fitted to the Robyn dataset."
        )
        example_data = pd.DataFrame({
            "Channel":     ["TV", "Facebook", "Search", "OOH"],
            "ROAS median": [1.82, 2.14, 3.41, 0.87],
            "HDI low":     [1.12, 1.31, 2.18, 0.41],
            "HDI high":    [2.71, 3.24, 4.89, 1.52],
        })
        channel_colors = {
            "TV": COLORS["tv"], "Facebook": COLORS["facebook"],
            "Search": COLORS["search"], "OOH": COLORS["ooh"],
        }
        fig = go.Figure()
        for _, row in example_data.iterrows():
            color = channel_colors.get(row["Channel"], "#888")
            fig.add_trace(go.Bar(
                x=[row["Channel"]],
                y=[row["ROAS median"]],
                error_y=dict(
                    type="data",
                    symmetric=False,
                    array=[row["HDI high"] - row["ROAS median"]],
                    arrayminus=[row["ROAS median"] - row["HDI low"]],
                ),
                marker_color=color,
                name=row["Channel"],
                text=f"{row['ROAS median']:.2f}x",
                textposition="outside",
            ))
        fig.update_layout(
            **PLOTLY_LAYOUT, height=360,
            yaxis_title="Incremental ROAS",
            showlegend=False,
        )
        st.plotly_chart(fig, width="stretch")

        st.markdown("**What this page shows when run locally:**")
        st.markdown(
            "- Posterior ROAS bars with 94% HDI error bars per channel\n"
            "- Violin plots of full posterior sample distributions\n"
            "- Counterfactual revenue chart: actual vs zero-TV-spend scenario\n"
            "- Total TV causal contribution in dollars with uncertainty shading"
        )

    else:
        # PyMC is available — run the full Bayesian model
        run_bayes = st.button(
            "Run Bayesian MMM sampling (~2 min)",
            help="MCMC sampling via PyMC. Runs once then cached automatically.",
        )

        if run_bayes or "bayes_ran" in st.session_state:
            st.session_state["bayes_ran"] = True

            with st.spinner(
                "Sampling posterior distributions via MCMC... "
                "(~2 min, cached after first run)"
            ):
                try:
                    from tvlift.bayesian_mmm import (
                        build_bayesian_mmm,
                        extract_channel_roas,
                        compute_counterfactual,
                    )
                    mmm, trace, rev_mean, rev_std, spend_arrays = build_bayesian_mmm(
                        df, adstock_params,
                        sample_kwargs={
                            "draws": 500,
                            "tune": 300,
                            "chains": 2,
                            "target_accept": 0.9,
                            "return_inferencedata": True,
                            "progressbar": False,
                        }
                    )
                    roas_df    = extract_channel_roas(
                        trace, df, spend_arrays, rev_mean, rev_std
                    )
                    counter_df = compute_counterfactual(
                        trace, df, spend_arrays, rev_mean, rev_std
                    )
                    success = True
                except Exception as e:
                    st.error(f"Bayesian sampling failed: {e}")
                    success = False
                    roas_df = counter_df = None

            if success and roas_df is not None:

                # Posterior ROAS bars with HDI error bars
                st.subheader("Posterior ROAS by channel")
                st.caption(
                    "Each bar = median ROAS. Error bars = 94% highest density interval. "
                    "Overlapping intervals = channels are statistically indistinguishable."
                )
                fig = go.Figure()
                for _, row in roas_df.iterrows():
                    ch    = row["channel"]
                    color = channel_colors.get(ch, "#888")
                    fig.add_trace(go.Bar(
                        x=[ch],
                        y=[row["roas_median"]],
                        error_y=dict(
                            type="data",
                            symmetric=False,
                            array=[row["roas_hdi_high"] - row["roas_median"]],
                            arrayminus=[row["roas_median"] - row["roas_hdi_low"]],
                        ),
                        marker_color=color,
                        name=ch,
                        text=f"{row['roas_median']:.2f}x",
                        textposition="outside",
                    ))
                fig.update_layout(
                    **PLOTLY_LAYOUT, height=360,
                    yaxis_title="Incremental ROAS",
                    showlegend=False,
                )
                st.plotly_chart(fig, width="stretch")

                # Violin plots — showing the full distribution shape,
                # not just the summary statistics
                st.subheader("Full posterior distributions")
                fig2 = go.Figure()
                for _, row in roas_df.iterrows():
                    ch      = row["channel"]
                    color   = channel_colors.get(ch, "#888")
                    samples = row["roas_samples"]
                    fig2.add_trace(go.Violin(
                        x=[ch] * len(samples),
                        y=samples,
                        name=ch,
                        box_visible=True,
                        meanline_visible=True,
                        fillcolor=color,
                        opacity=0.7,
                        line_color=color,
                    ))
                fig2.update_layout(
                    **PLOTLY_LAYOUT, height=360,
                    yaxis_title="ROAS samples",
                    showlegend=False,
                )
                st.plotly_chart(fig2, width="stretch")

                # Counterfactual — the most powerful chart in the project.
                # The shaded purple gap between actual and counterfactual
                # revenue is TV's total causal contribution in dollars.
                # This is the visual that closes the argument.
                if counter_df is not None:
                    st.subheader("Counterfactual: actual vs zero-TV-spend revenue")
                    st.caption(
                        "The shaded gap is TV's causal contribution to revenue. "
                        "This is the entire argument for why TV measurement exists."
                    )
                    fig3 = go.Figure()

                    # Uncertainty band around actual revenue
                    fig3.add_trace(go.Scatter(
                        x=counter_df["date"], y=counter_df["actual_hdi_high"],
                        mode="lines", line=dict(width=0),
                        showlegend=False, name="Actual upper",
                    ))
                    fig3.add_trace(go.Scatter(
                        x=counter_df["date"], y=counter_df["actual_hdi_low"],
                        fill="tonexty",
                        fillcolor=COLORS["uncertainty"],
                        line=dict(width=0),
                        showlegend=False, name="Actual lower",
                    ))
                    # Actual revenue
                    fig3.add_trace(go.Scatter(
                        x=counter_df["date"], y=counter_df["actual_median"],
                        line=dict(color=COLORS["actual"], width=2.5),
                        name="Actual revenue",
                    ))
                    # Counterfactual (zero TV spend)
                    fig3.add_trace(go.Scatter(
                        x=counter_df["date"], y=counter_df["counter_median"],
                        line=dict(color=COLORS["counter"], width=2, dash="dash"),
                        name="Without TV",
                    ))
                    # TV contribution shading — the purple gap
                    fig3.add_trace(go.Scatter(
                        x=pd.concat([
                            counter_df["date"],
                            counter_df["date"][::-1],
                        ]),
                        y=pd.concat([
                            counter_df["actual_median"],
                            counter_df["counter_median"][::-1],
                        ]),
                        fill="toself",
                        fillcolor="rgba(127,119,221,0.15)",
                        line=dict(width=0),
                        name="TV contribution",
                    ))

                    total_tv_contrib = counter_df["tv_contribution"].sum()
                    fig3.update_layout(
                        **PLOTLY_LAYOUT, height=420,
                        yaxis_title="Revenue ($)",
                        legend=dict(orientation="h", y=-0.2),
                        annotations=[dict(
                            x=counter_df["date"].median(),
                            y=counter_df["actual_median"].max() * 0.92,
                            text=f"Total TV contribution: "
                                 f"${total_tv_contrib/1e6:.1f}M",
                            showarrow=False,
                            font=dict(color=COLORS["tv"], size=13),
                        )],
                    )
                    st.plotly_chart(fig3, width="stretch")
        else:
            st.info(
                "Click the button above to run Bayesian MCMC sampling. "
                "Takes ~2 minutes and is cached after the first run."
            )



# PAGE 7 — DAYPART ANALYSIS
# "Does TV work?" is the wrong question.
# "Which TV slots work?" is what clients actually pay to know.
#
# This page moves from channel-level attribution to airing-level attribution —
# the granularity at which actual media buying decisions are made.
# Saturday primetime vs Tuesday late night = 7x ROAS difference.
# That's the entire case for data-driven TV buying.

elif page == "📺 Daypart analysis":
    st.title("Daypart × day-of-week ROAS analysis")
    st.info(
        "**The client question TV measurement platforms actually answer:** "
        "Not 'does TV work?' but 'which slots work?' "
        "Saturday primetime vs Tuesday late night can differ by 6x in ROAS. "
        "This analysis drives actual media buy decisions."
    )

    daypart_order = ["primetime", "daytime", "morning", "late_night"]
    day_order     = ["mon", "tue", "wed", "thu", "fri", "sat", "sun"]

    # ROAS heatmap — 4 dayparts × 7 days = 28 cells.
    # The color gradient immediately shows where the value is concentrated.
    # An interviewer can read the business insight in 3 seconds.
    st.subheader("ROAS heatmap by daypart and day of week")
    pivot = heatmap_df.pivot(
        index="daypart", columns="day_of_week", values="predicted_roas"
    ).reindex(index=daypart_order, columns=day_order)

    fig = go.Figure(go.Heatmap(
        z=pivot.values,
        x=[d.capitalize() for d in day_order],
        y=["Primetime", "Daytime", "Morning", "Late night"],
        colorscale="Purples",
        text=[[f"{v:.2f}x" for v in row] for row in pivot.values],
        texttemplate="%{text}",
        colorbar=dict(title="ROAS"),
    ))
    fig.update_layout(**PLOTLY_LAYOUT, height=360)
    st.plotly_chart(fig, width="stretch")
    st.caption(
        "Darker = higher ROAS. Saturday primetime is the peak. "
        f"Late night weekday is the floor. Daypart model R²: {daypart_r2:.2f}"
    )

    # Best/worst slots table — actionable output.
    # The recommendation is implicit: shift budget from bottom 5 to top 5.
    st.subheader("Best and worst 5 slots")
    col1, col2 = st.columns(2)

    with col1:
        st.markdown("**Top 5 slots**")
        top5 = (
            heatmap_df
            .nlargest(5, "predicted_roas")
            [["daypart", "day_of_week", "predicted_roas"]]
            .reset_index(drop=True)
        )
        top5.columns = ["Daypart", "Day", "ROAS"]
        st.dataframe(top5, use_container_width=True)

    with col2:
        st.markdown("**Bottom 5 slots**")
        bot5 = (
            heatmap_df
            .nsmallest(5, "predicted_roas")
            [["daypart", "day_of_week", "predicted_roas"]]
            .reset_index(drop=True)
        )
        bot5.columns = ["Daypart", "Day", "ROAS"]
        st.dataframe(bot5, use_container_width=True)

    # Average ROAS by daypart — the one-number-per-slot summary
    # that goes into a client recommendation deck
    st.subheader("Average ROAS by daypart")
    dp_avg = (
        heatmap_df
        .groupby("daypart")["predicted_roas"]
        .mean()
        .reindex(daypart_order)
        .reset_index()
    )
    fig2 = go.Figure(go.Bar(
        x=["Primetime", "Daytime", "Morning", "Late night"],
        y=dp_avg["predicted_roas"],
        marker_color=[
            COLORS["tv"], COLORS["facebook"],
            COLORS["search"], COLORS["ooh"],
        ],
        text=[f"{v:.2f}x" for v in dp_avg["predicted_roas"]],
        textposition="outside",
    ))
    fig2.update_layout(
        **PLOTLY_LAYOUT, height=320,
        yaxis_title="Predicted ROAS",
    )
    st.plotly_chart(fig2, width="stretch")

    # Key insight callout — the one sentence the interviewer should remember
    best_slot  = heatmap_df.loc[heatmap_df["predicted_roas"].idxmax()]
    worst_slot = heatmap_df.loc[heatmap_df["predicted_roas"].idxmin()]
    ratio      = best_slot["predicted_roas"] / (worst_slot["predicted_roas"] + 1e-9)
    st.info(
        f"**Key insight:** "
        f"{best_slot['daypart'].replace('_', ' ').title()} "
        f"{best_slot['day_of_week'].capitalize()} is your best slot at "
        f"{best_slot['predicted_roas']:.2f}x ROAS — "
        f"{ratio:.1f}x better than "
        f"{worst_slot['daypart'].replace('_', ' ').title()} "
        f"{worst_slot['day_of_week'].capitalize()} "
        f"({worst_slot['predicted_roas']:.2f}x). "
        "Shifting budget from bottom slots to top slots is the immediate, "
        "zero-cost optimization opportunity."
    )



# PAGE 8 — OPTIMIZER

# The payoff of everything before it.
# Every prior page was building toward this one question:
# given what we now know about TV's true incremental impact,
# how should we allocate next week's budget?
#
# The optimizer is only credible because the measurement is credible.
# That's the core argument of the entire project.

elif page == "💰 Optimizer":
    st.title("Budget optimizer — maximize incremental ROAS")
    st.info(
        "**The punchline:** You can only optimize what you can measure. "
        "Every prior page built up to this — the optimizer uses the "
        "adstock-corrected, saturation-aware model to find the allocation "
        "that maximizes predicted incremental revenue."
    )

    # Two-column layout: budget on the left (wide), channel bounds on the right
    col1, col2 = st.columns([2, 1])
    with col1:
        budget = st.slider(
            "Total weekly budget ($)",
            min_value=10_000, max_value=500_000,
            value=100_000, step=5_000,
            format="$%d",
        )
    with col2:
        st.markdown("**TV channel bounds**")
        # TV bounds are the most strategically important constraint.
        # In practice, brands have brand safety minimums (must spend at least X on TV
        # to maintain brand presence) and capacity maximums (only so much premium
        # inventory is available to buy).
        tv_min = st.slider("TV min %", 0, 60, 10)
        tv_max = st.slider("TV max %", 20, 90, 70)

    # Run the optimizer — grid search over all feasible allocations
    # within the specified channel bounds
    with st.spinner("Finding optimal allocation..."):
        result = optimize_budget(
            model, feature_cols, df,
            total_budget=budget,
            channel_bounds={
                "tv_S":       (tv_min / 100, tv_max / 100),
                "facebook_S": (0.10, 0.50),
                "search_S":   (0.10, 0.50),
            },
        )

    alloc   = result["optimal_allocation"]
    opt_rev = result["optimal_predicted_revenue"]
    eq_rev  = result["equal_split_revenue"]
    uplift  = result["revenue_uplift_pct"]

    # Three KPIs: optimal revenue, equal-split baseline, and the delta.
    # The delta (uplift %) is the value created by optimization.
    c1, c2, c3 = st.columns(3)
    c1.metric("Optimal predicted revenue", f"${opt_rev:,.0f}")
    c2.metric("Equal-split baseline",      f"${eq_rev:,.0f}")
    c3.metric(
        "Revenue uplift",
        f"{uplift:.1f}%",
        delta=f"+{uplift:.1f}% from smart allocation",
    )

    # Allocation bar chart — shows where the money goes.
    # The dotted baseline makes the deviation from equal-split visually obvious.
    st.subheader("Optimal spend allocation")
    labels = ["TV", "Facebook", "Search"]
    values = [alloc["tv_S"], alloc["facebook_S"], alloc["search_S"]]
    colors = [COLORS["tv"], COLORS["facebook"], COLORS["search"]]

    fig = go.Figure(go.Bar(
        x=labels, y=values,
        marker_color=colors,
        text=[f"${v:,.0f}\n({v/budget*100:.0f}%)" for v in values],
        textposition="outside",
    ))
    fig.add_hline(
        y=budget / 3, line_dash="dot",
        annotation_text="Equal split baseline",
        line_color="gray",
    )
    fig.update_layout(
        **PLOTLY_LAYOUT, height=340,
        yaxis_title="Spend ($)",
    )
    st.plotly_chart(fig, width="stretch")
    st.caption(
        "Search shows high model ROAS due to its correlation with high-intent "
        "conversion events. In production, channel allocations are constrained "
        "by historical capacity curves, brand-building objectives, and client "
        "commitments — pure ROAS optimization without these guardrails would "
        "over-index performance channels at the expense of brand health."
    )

    # ROAS landscape heatmap — shows the full optimization surface.
    # The darkest cell is the optimum. The gradient shows how steeply
    # revenue degrades as you move away from the optimal allocation.
    # A sharp gradient = the optimizer is highly sensitive to allocation.
    # A flat landscape = allocations are roughly equivalent (diversify more).
    st.subheader("ROAS landscape — TV share vs Facebook share")
    st.caption(
        "The darkest cell is the optimal allocation. "
        "The gradient shows how quickly predicted revenue degrades "
        "as you move away from the optimum — "
        "this is the cost of sub-optimal TV allocation."
    )
    all_res = result["all_results"]
    if not all_res.empty:
        all_res["tv_pct"] = (all_res["tv_S"] / budget * 100).round(0)
        all_res["fb_pct"] = (all_res["facebook_S"] / budget * 100).round(0)
        pivot = all_res.pivot_table(
            index="fb_pct", columns="tv_pct",
            values="predicted_revenue", aggfunc="max",
        )
        fig2 = go.Figure(go.Heatmap(
            z=pivot.values,
            x=pivot.columns.astype(str),
            y=pivot.index.astype(str),
            colorscale="Purples",
            colorbar=dict(title="Pred. revenue ($)"),
        ))
        fig2.update_layout(
            **PLOTLY_LAYOUT, height=400,
            xaxis_title="TV share (%)",
            yaxis_title="Facebook share (%)",
        )
        st.plotly_chart(fig2, width="stretch")